# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/mygit/CG_Project/project_cg/project_cg.cache/wt [current_project]
set_property parent.project_path D:/mygit/CG_Project/project_cg/project_cg.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/array_arith/proj_array_arith/solution1/impl/ip [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/imports/Summer Internship IIIT-H/cg_multiplier.v}
  {D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/imports/Summer Internship IIIT-H/cg_adder.v}
  {D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/imports/Summer Internship IIIT-H/cg_vect_multiplier.v}
}
synth_design -top vector_by_vector -part xc7vx485tffg1157-1
write_checkpoint -noxdef vector_by_vector.dcp
catch { report_utilization -file vector_by_vector_utilization_synth.rpt -pb vector_by_vector_utilization_synth.pb }
