# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/scalar_float_division/scalar_float_division.xci
# IP: The module: 'scalar_float_division' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/scalar_float_division/scalar_float_division_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalar_float_division'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/scalar_float_division/scalar_float_division.xci
# IP: The module: 'scalar_float_division' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/scalar_float_division/scalar_float_division_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalar_float_division'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
