# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/mygit/CG_Project/project_cg/project_cg.cache/wt [current_project]
set_property parent.project_path D:/mygit/CG_Project/project_cg/project_cg.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_repo_paths d:/array_arith/proj_array_arith/solution1/impl/ip [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/floating_point_0_1/floating_point_0.xci
set_property is_locked true [get_files d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/floating_point_0_1/floating_point_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top floating_point_0 -part xc7z020clg484-1 -mode out_of_context
rename_ref -prefix_all floating_point_0_
write_checkpoint -noxdef floating_point_0.dcp
catch { report_utilization -file floating_point_0_utilization_synth.rpt -pb floating_point_0_utilization_synth.pb }
if { [catch {
  file copy -force D:/mygit/CG_Project/project_cg/project_cg.runs/floating_point_0_synth_1/floating_point_0.dcp d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/floating_point_0_1/floating_point_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/floating_point_0_1/floating_point_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/floating_point_0_1/floating_point_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/floating_point_0_1/floating_point_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/floating_point_0_1/floating_point_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/mygit/CG_Project/project_cg/project_cg.ip_user_files/ip/floating_point_0]} {
  catch { 
    file copy -force d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/floating_point_0_1/floating_point_0_stub.v D:/mygit/CG_Project/project_cg/project_cg.ip_user_files/ip/floating_point_0
  }
}

if {[file isdir D:/mygit/CG_Project/project_cg/project_cg.ip_user_files/ip/floating_point_0]} {
  catch { 
    file copy -force d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/floating_point_0_1/floating_point_0_stub.vhdl D:/mygit/CG_Project/project_cg/project_cg.ip_user_files/ip/floating_point_0
  }
}
