# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/vect_float_sub/vect_float_sub.xci
# IP: The module: 'vect_float_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/vect_float_sub/vect_float_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vect_float_sub'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/vect_float_sub/vect_float_sub.xci
# IP: The module: 'vect_float_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/vect_float_sub/vect_float_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vect_float_sub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
