# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/fifo_matrix_A/fifo_matrix_A.xci
# IP: The module: 'fifo_matrix_A' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/fifo_matrix_A/fifo_matrix_A/fifo_matrix_A.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_matrix_A'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/fifo_matrix_A/fifo_matrix_A_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_matrix_A'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/fifo_matrix_A/fifo_matrix_A.xci
# IP: The module: 'fifo_matrix_A' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/fifo_matrix_A/fifo_matrix_A/fifo_matrix_A.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_matrix_A'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/ip/fifo_matrix_A/fifo_matrix_A_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_matrix_A'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
