# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/mygit/CG_Project/project_cg/project_cg.cache/wt [current_project]
set_property parent.project_path D:/mygit/CG_Project/project_cg/project_cg.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths d:/array_arith/proj_array_arith/solution1/impl/ip [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet D:/mygit/CG_Project/project_cg/project_cg.runs/floating_point_0_synth_1/floating_point_0.dcp
set_property used_in_implementation false [get_files D:/mygit/CG_Project/project_cg/project_cg.runs/floating_point_0_synth_1/floating_point_0.dcp]
add_files -quiet D:/mygit/CG_Project/project_cg/project_cg.runs/floating_point_1_synth_1/floating_point_1.dcp
set_property used_in_implementation false [get_files D:/mygit/CG_Project/project_cg/project_cg.runs/floating_point_1_synth_1/floating_point_1.dcp]
add_files -quiet D:/mygit/CG_Project/project_cg/project_cg.runs/vect_float_sub_synth_1/vect_float_sub.dcp
set_property used_in_implementation false [get_files D:/mygit/CG_Project/project_cg/project_cg.runs/vect_float_sub_synth_1/vect_float_sub.dcp]
add_files -quiet D:/mygit/CG_Project/project_cg/project_cg.runs/scalar_float_division_synth_1/scalar_float_division.dcp
set_property used_in_implementation false [get_files D:/mygit/CG_Project/project_cg/project_cg.runs/scalar_float_division_synth_1/scalar_float_division.dcp]
add_files -quiet D:/mygit/CG_Project/project_cg/project_cg.runs/fifo_matrix_A_synth_1/fifo_matrix_A.dcp
set_property used_in_implementation false [get_files D:/mygit/CG_Project/project_cg/project_cg.runs/fifo_matrix_A_synth_1/fifo_matrix_A.dcp]
add_files -quiet D:/mygit/CG_Project/project_cg/project_cg.runs/ephsilon_mult_synth_1/ephsilon_mult.dcp
set_property used_in_implementation false [get_files D:/mygit/CG_Project/project_cg/project_cg.runs/ephsilon_mult_synth_1/ephsilon_mult.dcp]
read_verilog -library xil_defaultlib {
  {D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/imports/Summer Internship IIIT-H/cg_adder.v}
  {D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/imports/Summer Internship IIIT-H/cg_multiplier.v}
  D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/new/cg_vector_subtractor.v
  {D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/imports/Summer Internship IIIT-H/cg_scalar_mult.v}
  D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/new/cg_scalar_division.v
  D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/new/cg_scalar_adder.v
  {D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/imports/Summer Internship IIIT-H/cg_vect_multiplier.v}
  D:/mygit/CG_Project/project_cg/project_cg.srcs/sources_1/new/cg_top.v
}
synth_design -top cg_top -part xc7z020clg484-1
write_checkpoint -noxdef cg_top.dcp
catch { report_utilization -file cg_top_utilization_synth.rpt -pb cg_top_utilization_synth.pb }
